version: ~> 1.0

services:
  - docker

import:
  - semantic-release/semantic-release:.travis/node.yml
  - semantic-release/semantic-release:.travis/node-versions.yml
  - semantic-release/semantic-release:.travis/codecov.yml

before_script: 
  - npm run lint
  - npm run build