version: ~> 1.0

services:
  - docker

language: node_js

node_js:
  - node

jobs:
  include:
    - stage: lint
      script: 
        - npm run lint

    - stage: build
      script:
      - npm run build

    - stage: test:unit
      script:
        - npm run test:unit && yarn codecov

    - stage: test:integration
      env:
        - TEST_NPM_REGISTRY=http://localhost:4873
        - NPM_USERNAME=username
        - NPM_EMAIL=test@test.com
        - NPM_PASSWORD=password
      before_script:
        - docker pull verdaccio/verdaccio
        - docker run -d -p 4873:4873 verdaccio/verdaccio
        - npm install -g npm-cli-login
        - npm-cli-login -u $NPM_USERNAME -p $NPM_PASSWORD -e $NPM_EMAIL -r $TEST_NPM_REGISTRY

      script:
        - npm run test:integration && yarn codecov
